services:
  - type: web
    name: cinema-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
    # Add your environment variables in Render dashboard:
    # - MONGODB_URI
    # - JWT_SECRET
    # - CORS_ORIGINS
